name: Test Build and Release

on:
  push:
    branches:
      - master

jobs:
  trigger-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Trigger build-and-release workflow
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: Build and Release Go-Easy
          token: ${{ secrets.GITHUB_TOKEN }} 